version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: job-portal
    container_name: job-portal
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
